name: permissionrequest
description: A new Flutter package project.
version: 1.0.1
homepage: none
publish_to: none
environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  hooks_riverpod: ^1.0.3
  geoflutterfire: ^3.0.2
  geolocator: ^9.0.1
  http: ^0.13.4
  permission_handler: ^10.0.0
  flutter_screenutil: ^5.5.3+2
  core_kosmos:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  ui_kosmos_v4:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  freezed: ^2.0.3
  auto_route_generator: ^4.2.0
  json_serializable: ^6.2.0
flutter:
  assets:
  - assets/
